title: Calgary Society for Equity in Techonology
email: l.oneill.gordon@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Calgary Society for Equity in Tech is a local volunteer-administered collective that offers low cost classes/events in technology to the Calgary community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cset.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
repository: brennanbrown/cset
twitter: cset
github: brennanbrown

port: 13130

# paginate: 4
# paginate_path: "/:num/"

google_analytics:
comments: false
disqus:

author:
author_pic:
author_bio: >-

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: "_posts"
      type:
    values:
      layout: "post"
  -
    scope:
      path: "_pages"
      type:
    values:
      layout: "page"


# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"